language: bash

env:
  global:
    - REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=plus3it
    - DEPLOY_SLUG=$OWNER/$REPO
    

jobs:
  include:
    - stage: test
      env:
        - JOB="JSON Lint/Format"
      install:
        - jq --version
      script:
        - make json.lint
    - stage: test
      env:
        - JOB="YAML Lint"
      install:
        - pip install --user yamllint
        - yamllint --version
      script:
        - make yaml.lint
